config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resource :user, only: [:show] do
    resources :bookings, only: [:index, :edit, :update]
    get 'bookings/:id/cancel', to: "bookings#cancel", as: :booking_cancel
  end

  namespace :users do
    resources :flats, only: [:create, :new, :destroy, :edit, :update]
    resources :bookings, only: [:index]
    get 'bookings/:id/reject', to: "bookings#reject", as: :booking_reject
    get 'bookings/:id/confirm', to: "bookings#confirm", as: :booking_confirm
  end

  resources :flats, only: [:index, :show] do
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, only: [:show]

  root to: "pages#home"

end

app/models/flat.rb
class Flat < ActiveRecord::Base
  belongs_to :user
  has_many :bookings
  validates :title, presence: true
  validates :address_numberstreet, presence: true
  validates :address_zip, presence: true
  validates :address_city, presence: true
  validates :night_price, presence: true
  validates :capacity, presence: true

  has_attached_file :picture,
    styles: { medium: "300x300#", thumb: "150x150#" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/

  geocoded_by :full_address
  after_validation :geocode, if: ->(flat){
    flat.address_numberstreet.present? && flat.address_numberstreet_changed?
    flat.address_zip.present? && flat.address_zip_changed?
    flat.address_city.present? && flat.address_city_changed?
  }


  def full_address
    "#{address_numberstreet} #{address_zip} #{address_city}"
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    #@flats = Flat.where("LOWER(address_city) = :city AND capacity >= :guests", city: params[:city].downcase, guests: params[:guests])
    @guests = params[:guests]
    if params[:city].present? && params[:guests].present?
      @flats = Flat.near(params[:city].downcase, 500).where("capacity >= ?", params[:guests])
    elsif params[:city].present? && !params[:guests].present?
      @flats = Flat.near(params[:city].downcase, 500)
    else
      @flats = Flat.all
    end
    @markers = Gmaps4rails.build_markers(@flats) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
      marker.infowindow "<img src=#{flat.picture.url(:thumb)} alt=""> <br> <h5 class='text-center text-primary'><strong>#{flat.night_price} &euro; per night</strong></h5>"
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @flat_coordinates = [{ lat: @flat.latitude, lng: @flat.longitude }]
  end
end

app/controllers/users/flats_controller.rb
module Users
  class FlatsController < ApplicationController

    before_action :authenticate_user!

    def new
      @flat = Flat.new
    end

    def create
      @flat = current_user.flats.build(flat_params)
      if @flat.save
        redirect_to user_path
      else
        render :new
      end
    end

    def edit
      @flat = current_user.flats.find(params[:id])
    end

    def update
      @flat = current_user.flats.find(params[:id])
      @flat.update(flat_params)
      redirect_to user_path
    end

    def destroy
      @flat = current_user.flats.find(params[:id])
      @flat.destroy
      redirect_to :back
    end

    private

    def flat_params
      params.require(:flat).permit(:title, :description, :address_numberstreet, :address_city, :address_zip, :night_price, :capacity, :picture)
    end

  end
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="bg-wood">
<div class="text-center">
  <br>
  <h1>Your search results</h1>
</div>
<br>
<br>
<br>
<div class="container bg-darker-grey">
  <br>
  <br>
  <div class="row">
    <% @flats.each do |flat| %>
        <div class="col-xs-12 col-lg-6">
          <div class="row">
            <div class="col-xs-1"></div>
            <div class="col-xs-10 white-card-250">
          <div class="col-xs-6 text-center">
            <%= image_tag flat.picture.url(:thumb) %>
          </div>
          <div class="col-xs-6 text-center">
            <h4><%=link_to flat.title, flat_path(flat) %></h4>
            <br>
            <p><%= "Night price: #{flat.night_price} €" %></p>
            <p><%= "Capacity: #{flat.capacity} people" %></p>
            <p><%= "Owner: #{flat.user.first_name} #{flat.user.last_name}" %><%= image_tag flat.user.picture.url(:thumb), class: "img-small-round" %></p>
          </div>
        </div>
        <div class="col-xs-1"></div>
        </div>
        </div>
    <% end %>
</div>
<br>
<br>
<div id="map" style="width: 100%; height: 600px;"></div>
</div>
<br>
<br>
<br>
<br>
<br>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

</div>

app/views/flats/new.html.erb
<h1>Create a new flat</h1>

<%= simple_form_for(@flat, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :address_numberstreet %>
  <%= f.input :address_zip %>
  <%= f.input :address_city %>
  <%= f.input :address_state %>
  <%= f.input :address_country %>
  <%= f.input :night_price, label: "price per night in euro" %>

  <%= f.button :submit %>
<% end %>

app/views/flats/show.html.erb
<div class="bg-wood">
  <br>
<div class="text-center">
<h1><%= @flat.title%></h1>
</div>
<br>
<br>
<br>
<div class="container bg-darker-grey">
  <br>
  <br>
      <div class="row">
        <div class="col-xs-1"></div>
        <div class="col-xs-10">
          <div class="row white-card">
            <div class="col-xs-12 col-sm-6">
              <%= image_tag @flat.picture.url(:medium) %>
            </div>
            <div class="col-xs-12 col-sm-6">
              <h4><%= @flat.title %></h4>
              <br>
              <p><%= @flat.description %></p>
              <p>Adress: </p>
              <p><%= @flat.address_numberstreet %></p>
              <p><%= "#{@flat.address_zip} #{@flat.address_city}" %></p>
              <p><%= "Night price: #{@flat.night_price} €" %></p>
              <p><%= "Capacity: #{@flat.capacity} people" %></p>
              <p><%= "Host: #{@flat.user.first_name} #{@flat.user.last_name}" %></p>
            </div>
          </div>
        </div>
        <div class="col-xs-1"></div>
      </div>
    <div class="row text-center">
      <%= link_to "Book now!", new_flat_booking_path(@flat), class: "btn btn-primary" %>
    </div>
<br>
<div id="map" style='width: 100%; height: 600px;'></div>
</div>
<br>
<br>
<br>
<br>
<br>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @flat_coordinates.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(14);
      });
    })
  <% end %>
<% end %>
</div>