config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resource :user, only: [:show] do
    resources :bookings, only: [:index, :edit, :update]
    get 'bookings/:id/cancel', to: "bookings#cancel", as: :booking_cancel
  end

  namespace :users do
    resources :flats, only: [:create, :new, :destroy, :edit, :update]
    resources :bookings, only: [:index]
    get 'bookings/:id/reject', to: "bookings#reject", as: :booking_reject
    get 'bookings/:id/confirm', to: "bookings#confirm", as: :booking_confirm
  end

  resources :flats, only: [:index, :show] do
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, only: [:show]

  root to: "pages#home"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :flat
  validates :guests, presence: true
  validates :check_in, presence: true
  validates :check_out, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_flat, only: [:new, :create]
  before_action :find_booking, only: [:edit, :cancel, :update, :confirm, :reject]

  def index
    @bookings = []
      current_user.bookings.each do |booking|
        @bookings << booking
      end
      @bookings.sort_by! {|booking| -(booking.updated_at).to_f}
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @today = Date.today.strftime('%d-%m-%Y')
    @booking = Booking.new
  end

  def create
    @booking = @flat.bookings.build(booking_params)
    @booking.user = current_user
    @booking.status = "Pending"
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit

  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def cancel
    @booking.status = "Cancelled"
    @booking.save
    @flat = @booking.flat
    redirect_to booking_path(@booking)
  end

  def destroy

  end

  private

  def booking_params
    params.require(:booking).permit(:guests, :check_in, :check_out, :message, :status)
  end

  def find_flat
    @flat = Flat.find(params[:flat_id])
  end

  def find_booking
    @booking = current_user.bookings.find(params[:id])
  end

end

app/controllers/users/bookings_controller.rb
module Users
  class BookingsController < ApplicationController

    before_action :authenticate_user!
    before_action :find_requests

    def reject
      @booking = Booking.find(params[:id])
      @booking.status = "Rejected"
      @booking.save
      @flat = @booking.flat
      redirect_to users_bookings_path
    end

    def confirm
      @booking = Booking.find(params[:id])
      @booking.status = "Confirmed"
      @booking.save
      redirect_to users_bookings_path
    end

    def index
    end

    private

    def find_requests
      @requests = []
      current_user.flats.each do |flat|
        flat.bookings.each do |booking|
          @requests << booking
        end
      end
      @requests.sort_by! {|request| -(request.updated_at).to_f}
    end

  end
end

app/views/bookings/edit.html.erb
<div class="bg-wood">
  <br>
<div class="container">
  <div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
<h1>Edit booking</h1>

<%= simple_form_for(@booking, url: user_booking_path(@booking)) do |f| %>
  <%= f.error_notification %>

  <%= f.input :guests, label: "Number of guests" %>
  <%= f.input :check_in, as: :string, :input_html => { :data => {:provide => :datepicker, 'date-format': "dd/mm/yyyy"} } %>
  <%= f.input :check_out, as: :string, :input_html => { :data => {:provide => :datepicker, 'date-format': "dd/mm/yyyy"} } %>
  <%= f.input :message %>
  <p><%= f.button :submit %></p>
<% end %>
  <p><%= link_to "Cancel your booking", booking_cancel_user_path(@booking), class: "btn btn-danger" %></p>
  </div>
  <div class="col-xs-2"></div>
</div>
</div>
</div>

app/views/bookings/index.html.erb
<div class="bg-wood">
  <br>
<div class="text-center">
<h1><%= "Your travels" %></h1>
</div>
<br>
<br>
<br>
<div class="container bg-darker-grey">
  <br>
    <% @bookings.each do |booking| %>
      <div class="row">
        <div class="col-xs-2"></div>
        <div class="col-xs-8">
          <div class="row white-card">
            <div class="col-xs-12 col-md-6 text-center">
              <%= image_tag booking.flat.picture.url(:medium), class: "img-round" %>
            </div>
            <div class="col-xs-12 col-md-6 text-center">
              <h4><%= booking.flat.title %></h4>
              <p><%= booking.flat.address_numberstreet %></p>
              <p><%= booking.flat.address_city %></p>
              <p>Check in: <%= booking.check_in.strftime('%B %-d %Y') %></p>
              <p>Check out: <%= booking.check_out.strftime('%B %-d %Y') %></p>
              <p>Guests: <%= booking.guests %></p>
              <p>Price: <strong><%= (booking.flat.night_price * (booking.check_out - booking.check_in).to_i) %> &euro;</p></strong>
              <div class="row grey-card-150">
                <div class="col-xs-12">
                  <p><%= "Owner: #{booking.flat.user.first_name} #{booking.flat.user.last_name}" %></p>
                  <%= image_tag booking.flat.user.picture.url(:thumb), class: "img-small-round" %>
                  <%= booking.flat.user.email %>
                </div>
              </div>
            </div>
            <div class="col-xs-12 text-center">
              <div class="text-center">
                <h4>Booking status:</h4>
              </div>
              <% if booking.status == "Pending" %>
                <h4 class="text-muted"><strong><%= "Pending..." %></strong></h4>
                <br>
                <%= link_to "Cancel booking request",  booking_cancel_user_path(booking), class: "text-danger"%>
              <% elsif booking.status == "Cancelled" %>
                <h4 class="text-danger"><strong><%= "Cancelled by you" %></strong></h4>
              <% elsif booking.status == "Rejected" %>
                <h4 class="text-danger"><strong><%= "Rejected by owner" %></strong></h4>
              <% elsif booking.status == "Confirmed" %>
                <h4 class="text-success"><strong><%= "Confirmed by owner" %></strong></h4>
                <br>
                <%= link_to "Cancel booking request",  booking_cancel_user_path(booking), class: "btn btn-danger"%>
              <% end %>
            </div>
            </div>
          </div>
          <div class="col-xs-2"></div>
        </div>
        <% end %>
        <br>
      </div>
<br>
<br>
<br>
<br>
</div>

app/views/bookings/new.html.erb
<div class="bg-wood">
  <br>
<div class="container">
  <div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8">
<h1>Book <%= @flat.title %></h1>


<%= simple_form_for(@booking, url: flat_bookings_path) do |f| %>
  <%= f.error_notification %>
  <% guests_choice = [] %>
  <%(1..@flat.capacity).each {|number| guests_choice << number} %>
  <%= f.input :guests, :label => "Number of guests", :collection => guests_choice %>
  <%= f.input :check_in, as: :string, :input_html => { :data => {:provide => :datepicker, 'date-format': "dd/mm/yyyy", 'date-start-date': Date.today.strftime('%d-%m-%Y'), 'date-autoclose': true} } %>
  <%= f.input :check_out, as: :string, :input_html => { :data => {:provide => :datepicker, 'date-format': "dd/mm/yyyy", 'date-start-date': Date.today.strftime('%d-%m-%Y'), 'date-autoclose': true} } %>
  <%= f.input :message, label: "Leave a message for #{@flat.user.first_name} #{@flat.user.last_name}" %>
  <p><%= f.button :submit %></p>
<% end %>
  </div>
  <div class="col-xs-2"></div>
</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>

app/views/bookings/show.html.erb
<div class="bg-wood">
  <br>
<div class="text-center">
<h1>Booking summary</h1>
</div>
<br>
<br>
<br>
<div class="container bg-darker-grey text-center">
  <br>
      <div class="row">
        <div class="col-xs-2"></div>
        <div class="col-xs-8">
          <div class="row white-card">
            <div class="col-xs-12 col-sm-6">
              <%= image_tag @booking.flat.picture.url(:medium) %>
            </div>
            <div class="col-xs-12 col-sm-6">
              <h4><%= @booking.flat.title %></h4>
              <p>Check in: <%= @booking.check_in.strftime('%B %-d %Y') %></p>
              <p>Check out: <%= @booking.check_out.strftime('%B %-d %Y') %></p>
              <p>Guests: <%= @booking.guests %></p>
              <p>Status: <%= @booking.status %></p>

              <p>
                <%= @booking.flat.night_price %> &euro; x <%= (@booking.check_out - @booking.check_in).to_i %> nights
                <br>
                <strong>Total: <%= (@booking.flat.night_price * (@booking.check_out - @booking.check_in).to_i) %> &euro;</strong>
              </p>
              <p><strong>Status: <%= @booking.status %></strong></p>
              <p><%= link_to "Back to my bookings", user_bookings_path, class: "btn btn-primary" %></p>
            </div>
          </div>
        </div>
        <div class="col-xs-2"></div>
      </div>
<br>
</div>
<br>
<br>
<br>
<br>
<br>
</div>