config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resource :user, only: [:show] do
    resources :bookings, only: [:index, :edit, :update]
    get 'bookings/:id/cancel', to: "bookings#cancel", as: :booking_cancel
  end

  namespace :users do
    resources :flats, only: [:create, :new, :destroy, :edit, :update]
    resources :bookings, only: [:index]
    get 'bookings/:id/reject', to: "bookings#reject", as: :booking_reject
    get 'bookings/:id/confirm', to: "bookings#confirm", as: :booking_confirm
  end

  resources :flats, only: [:index, :show] do
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, only: [:show]

  root to: "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :flats
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [ :facebook ]

  has_attached_file :picture,
    styles: { medium: "300x300#", thumb: "100x100#" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/


  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.name = auth.info.name
      user.picture = process_uri(auth.info.image)
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  def self.process_uri(uri)
     avatar_url = URI.parse(uri)
     avatar_url.scheme = 'https'
     avatar_url.to_s
  end

  private

end

app/controllers/users/bookings_controller.rb
module Users
  class BookingsController < ApplicationController

    before_action :authenticate_user!
    before_action :find_requests

    def reject
      @booking = Booking.find(params[:id])
      @booking.status = "Rejected"
      @booking.save
      @flat = @booking.flat
      redirect_to users_bookings_path
    end

    def confirm
      @booking = Booking.find(params[:id])
      @booking.status = "Confirmed"
      @booking.save
      redirect_to users_bookings_path
    end

    def index
    end

    private

    def find_requests
      @requests = []
      current_user.flats.each do |flat|
        flat.bookings.each do |booking|
          @requests << booking
        end
      end
      @requests.sort_by! {|request| -(request.updated_at).to_f}
    end

  end
end

app/controllers/users/flats_controller.rb
module Users
  class FlatsController < ApplicationController

    before_action :authenticate_user!

    def new
      @flat = Flat.new
    end

    def create
      @flat = current_user.flats.build(flat_params)
      if @flat.save
        redirect_to user_path
      else
        render :new
      end
    end

    def edit
      @flat = current_user.flats.find(params[:id])
    end

    def update
      @flat = current_user.flats.find(params[:id])
      @flat.update(flat_params)
      redirect_to user_path
    end

    def destroy
      @flat = current_user.flats.find(params[:id])
      @flat.destroy
      redirect_to :back
    end

    private

    def flat_params
      params.require(:flat).permit(:title, :description, :address_numberstreet, :address_city, :address_zip, :night_price, :capacity, :picture)
    end

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users

  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

      if user.persisted?
        sign_in_and_redirect user, event: :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="bg-wood">
  <br>
<div class="text-center">
<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
<h2><%= @user.email%></h2>
<%= image_tag @user.picture.url(:medium), class: "img-round"%>
</div>
<br>
<br>
<br>
<div class="container bg-darker-grey">
  <div class="row text-center"><h3>Flats</h3></div>
    <% @user.flats.each do |flat| %>
      <div class="row">
        <div class="col-xs-1"></div>
        <div class="col-xs-10">
          <div class="row white-card">
            <div class="col-xs-12 col-sm-6 text-center">
              <%= image_tag flat.picture.url(:medium) %>
            </div>
            <div class="col-xs-12 col-sm-6 text-center">
              <h4><%= flat.title %></h4>
              <br>
              <p><%= flat.description %></p>
              <p>Adress: </p>
              <p><%= flat.address_numberstreet %></p>
              <p><%= "#{flat.address_zip} #{flat.address_city}" %></p>
              <p><%= "Night price: #{flat.night_price} €" %></p>
              <p><%= "Capacity: #{flat.capacity} people" %></p>
              <%= link_to "Edit flat", edit_users_flat_path(flat), class: "btn btn-warning" %>
              <%= link_to "Delete flat", users_flat_path(flat),
                          method: :delete,
                          data: { confirm: "Are you sure?" },
                          class: "btn btn-danger"%>
            </div>
          </div>
        </div>
        <div class="col-xs-1"></div>
      </div>
    <% end %>
    <div class="row text-center">
      <%= link_to "Add new flat", new_users_flat_path, class: "btn btn-primary"%>
    </div>
<br>
</div>
<br>
<br>
<br>
<br>
<br>
</div>