config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resource :user, only: [:show] do
    resources :bookings, only: [:index, :edit, :update]
    get 'bookings/:id/cancel', to: "bookings#cancel", as: :booking_cancel
  end

  namespace :users do
    resources :flats, only: [:create, :new, :destroy, :edit, :update]
    resources :bookings, only: [:index]
    get 'bookings/:id/reject', to: "bookings#reject", as: :booking_reject
    get 'bookings/:id/confirm', to: "bookings#confirm", as: :booking_confirm
  end

  resources :flats, only: [:index, :show] do
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, only: [:show]

  root to: "pages#home"

end

app/views/shared/_alerts.html.erb
<% if alert %>
  <div class="alert alert-info alert-dismissible no-margin" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="bg-green">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div id="social-links" class="pull-left">
          <ul class="list-inline">
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-facebook"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-twitter"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-youtube"></i>
              <% end %>
            </li>
          </ul>
        </div>

        <div class="pull-right">
          <span>&copy; Robinson</span>
        </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_likeshare.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '948136108541192',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "logo.png" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              <% if current_user.uid.present? %>
                <%= image_tag current_user.picture, class: "img-avatar" %>
              <% else %>
                <%= image_tag current_user.picture.url(:thumb), class: "img-avatar" %>
                 <% if notifications > 0 %>
                    <div class="notif" id="notifications-main-div">
                      <div id="notifications-number-div">
                        <strong><%= notifications %></strong>
                      </div>
                    </div>
                  <% end %>
              <% end %>
              Profile <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to user_path do %>
                  <i class="fa fa-user"></i> <%= t ".profile", default: "Profile & flats" %>
                <% end %>
              </li>
              <li>
                <%= link_to user_bookings_path do %>
                  <i class="fa fa-plane"></i>  <%= t ".profile", default: "My travels" %>
                  <% if notif_bookings > 0 %>
                    <div class="notif" id="bookings-main-div">
                      <div id="bookings-number-div">
                        <strong><%= notif_bookings %></strong>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </li>
              <li>
                <%= link_to users_bookings_path do %>
                  <i class="fa fa-home"></i>  <%= t ".profile", default: "My requests" %>
                  <% if notif_requests > 0 %>
                    <div class="notif" id="requests-main-div">
                      <div id="requests-number-div">
                        <strong><%= notif_requests %></strong>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Sign out" %>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path %>
          </li>
          <li>
            <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path %>
          </li>
          <li>
            <%= link_to "Connect with Facebook", user_omniauth_authorize_path(:facebook) %>
          </li>
        <% end %>
        <li>
          <%= link_to "Rent your place now!", new_users_flat_path, class: "btn" %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible no-margin" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>